// The draw pool for every generated test: the ~200 most common words of each
// language, the way monkeytype ships one word list per language. Deriving the
// pool from sample sentences instead left roughly 120 words, so a 50-word test
// repeated most of them.
//
// Rules for anything added here: lowercase, no spaces, no digits and no
// sentence punctuation - capitals, commas and numbers are what the punctuation
// and numbers options put on top.

export const LANGUAGES = {
  english: {
    label: 'English',
    words: [
      'the', 'be', 'of', 'and', 'a', 'to', 'in', 'he', 'have', 'it', 'that', 'for', 'they', 'with', 'as', 'not',
      'on', 'she', 'at', 'by', 'this', 'we', 'you', 'do', 'but', 'from', 'or', 'which', 'one', 'would', 'all',
      'will', 'there', 'say', 'who', 'make', 'when', 'can', 'more', 'if', 'no', 'man', 'out', 'other', 'so',
      'what', 'time', 'up', 'go', 'about', 'than', 'into', 'could', 'state', 'only', 'new', 'year', 'some',
      'take', 'come', 'these', 'know', 'see', 'use', 'get', 'like', 'then', 'first', 'any', 'work', 'now',
      'may', 'such', 'give', 'over', 'think', 'most', 'even', 'find', 'day', 'also', 'after', 'way', 'many',
      'must', 'look', 'before', 'great', 'back', 'through', 'much', 'where', 'your', 'own', 'should', 'well',
      'people', 'down', 'just', 'because', 'good', 'each', 'those', 'feel', 'seem', 'how', 'high', 'too',
      'place', 'little', 'world', 'very', 'still', 'nation', 'hand', 'old', 'life', 'tell', 'write', 'become',
      'here', 'show', 'house', 'both', 'between', 'need', 'mean', 'call', 'develop', 'under', 'last', 'right',
      'move', 'thing', 'general', 'school', 'never', 'same', 'another', 'begin', 'while', 'number', 'part',
      'turn', 'real', 'leave', 'might', 'want', 'point', 'form', 'off', 'child', 'few', 'small', 'since',
      'against', 'ask', 'late', 'home', 'interest', 'large', 'person', 'end', 'open', 'public', 'follow',
      'during', 'present', 'without', 'again', 'hold', 'govern', 'around', 'possible', 'head', 'consider',
      'word', 'program', 'problem', 'however', 'lead', 'system', 'set', 'order', 'eye', 'plan', 'run', 'keep',
      'face', 'fact', 'group', 'play', 'stand', 'increase', 'early', 'course', 'change', 'help', 'line',
      'city', 'put', 'close', 'case', 'force', 'meet', 'once', 'water', 'upon', 'war', 'build', 'hear',
      'light', 'unite', 'live', 'every', 'country', 'bring', 'center', 'let', 'side', 'try', 'provide',
      'continue', 'name', 'certain', 'power', 'pay', 'result', 'question', 'study', 'woman', 'member',
      'until', 'far', 'night', 'always', 'service', 'away', 'report', 'something', 'company', 'week',
      'church', 'toward', 'start', 'social', 'room', 'figure', 'nature', 'though', 'young', 'less', 'enough',
      'almost', 'read', 'include', 'president', 'nothing', 'yet', 'better', 'big', 'boy', 'cost', 'business',
      'value', 'second', 'why', 'clear', 'expect', 'family', 'complete', 'act', 'sense', 'mind', 'experience',
      'art', 'next', 'near', 'direct', 'car', 'law', 'industry', 'important', 'girl', 'god', 'several',
      'matter', 'usual', 'thus', 'level', 'particular', 'book', 'whether', 'control', 'common', 'necessary',
      'policy', 'simple', 'door', 'wife', 'front', 'office', 'rather', 'body', 'machine', 'idea',
    ],
  },
  uzbek: {
    label: 'O‘zbek',
    words: [
      'va', 'bir', 'bu', 'uchun', 'ham', 'bilan', 'men', 'sen', 'biz', 'siz', 'ular', 'kun', 'yil', 'ish',
      'inson', 'odam', 'bola', 'ona', 'ota', 'oila', 'uy', 'shahar', 'yurt', 'davlat', 'xalq', 'til', 'so‘z',
      'kitob', 'maktab', 'talaba', 'o‘qituvchi', 'dars', 'bilim', 'fan', 'savol', 'javob', 'yo‘l', 'ko‘cha',
      'suv', 'havo', 'quyosh', 'osmon', 'yer', 'tog‘', 'daraxt', 'bog‘', 'gul', 'non', 'choy', 'ovqat',
      'vaqt', 'soat', 'hafta', 'oy', 'kecha', 'ertaga', 'bugun', 'hozir', 'keyin', 'avval', 'doim', 'ba’zan',
      'yana', 'faqat', 'lekin', 'ammo', 'agar', 'chunki', 'shuning', 'barcha', 'har', 'ko‘p', 'oz', 'katta',
      'kichik', 'yangi', 'eski', 'yaxshi', 'yomon', 'go‘zal', 'tez', 'sekin', 'oson', 'qiyin', 'to‘g‘ri',
      'noto‘g‘ri', 'baland', 'past', 'uzoq', 'yaqin', 'birinchi', 'ikkinchi', 'oxirgi', 'butun', 'yarim',
      'qilmoq', 'bo‘lmoq', 'kelmoq', 'ketmoq', 'bermoq', 'olmoq', 'ko‘rmoq', 'bilmoq', 'aytmoq', 'yozmoq',
      'o‘qimoq', 'ishlamoq', 'yashamoq', 'o‘ylamoq', 'tushunmoq', 'topmoq', 'qo‘ymoq', 'turmoq', 'yurmoq',
      'boshlamoq', 'tugatmoq', 'kutmoq', 'sevmoq', 'istamoq', 'kerak', 'mumkin', 'zarur', 'muhim', 'oson',
      'ishonch', 'maqsad', 'natija', 'sabab', 'fikr', 'reja', 'imkoniyat', 'muammo', 'yechim', 'tajriba',
      'mehnat', 'kuch', 'sabr', 'umid', 'sevgi', 'do‘st', 'dushman', 'hayot', 'o‘lim', 'sog‘lik', 'baxt',
      'quvonch', 'g‘am', 'orzu', 'kelajak', 'o‘tmish', 'hozirgi', 'tarix', 'madaniyat', 'san’at', 'musiqa',
      'kino', 'rasm', 'raqam', 'son', 'narx', 'pul', 'bozor', 'do‘kon', 'mahsulot', 'xizmat', 'kompyuter',
      'telefon', 'internet', 'dastur', 'tizim', 'texnologiya', 'ma’lumot', 'xabar', 'yangilik', 'jamiyat',
      'guruh', 'jamoa', 'rahbar', 'ishchi', 'kasb', 'vazifa', 'huquq', 'qonun', 'adolat', 'erkinlik',
      'tinchlik', 'do‘stlik', 'hurmat', 'mas’uliyat', 'tartib', 'qoida', 'daraja', 'sifat', 'miqdor',
      'o‘lcham', 'shakl', 'rang', 'oq', 'qora', 'qizil', 'ko‘k', 'yashil', 'sariq', 'issiq', 'sovuq',
      'yozgi', 'qishki', 'bahor', 'kuz', 'shamol', 'yomg‘ir', 'qor', 'dengiz', 'daryo', 'ko‘l', 'tuproq',
      'hayvon', 'qush', 'baliq', 'mushuk', 'it', 'ot', 'meva', 'olma', 'uzum', 'tarvuz', 'sabzavot',
      'guruch', 'go‘sht', 'sut', 'asal', 'shirin', 'achchiq', 'nordon', 'ta’m', 'hid', 'ovoz', 'kuy',
      'qo‘shiq', 'she’r', 'hikoya', 'roman', 'muallif', 'sahifa', 'harf', 'jumla', 'matn', 'tarjima',
    ],
  },
  russian: {
    label: 'Русский',
    words: [
      'и', 'в', 'не', 'на', 'я', 'быть', 'он', 'с', 'что', 'а', 'по', 'это', 'она', 'этот', 'к', 'но', 'они',
      'мы', 'как', 'из', 'у', 'который', 'то', 'за', 'свой', 'весь', 'год', 'от', 'так', 'для', 'ты', 'же',
      'все', 'тот', 'мочь', 'вы', 'человек', 'такой', 'его', 'сказать', 'только', 'или', 'ещё', 'бы', 'себя',
      'один', 'как', 'уже', 'до', 'время', 'если', 'сам', 'когда', 'другой', 'вот', 'говорить', 'наш',
      'мой', 'знать', 'стать', 'при', 'чтобы', 'дело', 'жизнь', 'кто', 'первый', 'очень', 'два', 'день',
      'её', 'новый', 'рука', 'даже', 'во', 'со', 'раз', 'где', 'там', 'под', 'можно', 'после', 'их', 'работа',
      'без', 'самый', 'потом', 'надо', 'хотеть', 'ли', 'слово', 'идти', 'большой', 'должен', 'место',
      'иметь', 'ничто', 'потому', 'здесь', 'думать', 'каждый', 'сторона', 'дом', 'друг', 'сейчас',
      'между', 'через', 'видеть', 'нужно', 'три', 'сделать', 'жить', 'смотреть', 'ребёнок', 'более', 'город',
      'вопрос', 'голова', 'вода', 'страна', 'конец', 'хороший', 'случай', 'глаз', 'система', 'также',
      'путь', 'земля', 'мир', 'лицо', 'друг', 'сила', 'ночь', 'часть', 'никто', 'помочь', 'деньги', 'книга',
      'утро', 'дорога', 'ответ', 'мысль', 'решение', 'причина', 'пример', 'число', 'группа', 'уровень',
      'развитие', 'работать', 'понимать', 'читать', 'писать', 'играть', 'учиться', 'начать', 'найти',
      'взять', 'дать', 'держать', 'открыть', 'закрыть', 'ждать', 'любить', 'жизнь', 'семья', 'школа',
      'учитель', 'ученик', 'улица', 'машина', 'окно', 'дверь', 'стол', 'стул', 'свет', 'воздух', 'солнце',
      'небо', 'дерево', 'цветок', 'море', 'река', 'лес', 'гора', 'снег', 'дождь', 'ветер', 'зима', 'лето',
      'весна', 'осень', 'белый', 'чёрный', 'красный', 'синий', 'зелёный', 'простой', 'сложный', 'быстро',
      'медленно', 'сильный', 'слабый', 'молодой', 'старый', 'высокий', 'низкий', 'далеко', 'близко',
      'всегда', 'никогда', 'иногда', 'снова', 'вместе', 'кроме', 'против', 'среди', 'почти', 'скорее',
    ],
  },
  turkish: {
    label: 'Türkçe',
    words: [
      'bir', 've', 'bu', 'için', 'ile', 'ben', 'sen', 'biz', 'siz', 'onlar', 'çok', 'daha', 'ama', 'gibi',
      'kadar', 'sonra', 'önce', 'her', 'şey', 'zaman', 'gün', 'yıl', 'insan', 'kişi', 'çocuk', 'anne',
      'baba', 'aile', 'ev', 'okul', 'iş', 'şehir', 'ülke', 'dünya', 'yol', 'su', 'hava', 'güneş', 'gök',
      'yer', 'dağ', 'ağaç', 'çiçek', 'deniz', 'nehir', 'orman', 'kitap', 'kelime', 'dil', 'ses', 'göz',
      'el', 'baş', 'yüz', 'kalp', 'can', 'hayat', 'ölüm', 'sevgi', 'dost', 'arkadaş', 'sorun', 'çözüm',
      'soru', 'cevap', 'fikir', 'düşünce', 'amaç', 'sonuç', 'sebep', 'örnek', 'sayı', 'para', 'fiyat',
      'pazar', 'ürün', 'hizmet', 'iyi', 'kötü', 'güzel', 'büyük', 'küçük', 'yeni', 'eski', 'uzun', 'kısa',
      'hızlı', 'yavaş', 'kolay', 'zor', 'doğru', 'yanlış', 'açık', 'kapalı', 'yüksek', 'alçak', 'uzak',
      'yakın', 'ilk', 'son', 'tüm', 'bazı', 'başka', 'aynı', 'kendi', 'olmak', 'yapmak', 'gelmek',
      'gitmek', 'vermek', 'almak', 'görmek', 'bilmek', 'demek', 'söylemek', 'yazmak', 'okumak', 'çalışmak',
      'yaşamak', 'düşünmek', 'anlamak', 'bulmak', 'koymak', 'durmak', 'kalmak', 'başlamak', 'bitirmek',
      'beklemek', 'sevmek', 'istemek', 'gerek', 'lazım', 'mümkün', 'önemli', 'zorunlu', 'birlikte',
      'sadece', 'yine', 'hâlâ', 'artık', 'şimdi', 'bugün', 'yarın', 'dün', 'gece', 'sabah', 'akşam',
      'hafta', 'ay', 'saat', 'dakika', 'geçen', 'gelecek', 'geçmiş', 'tarih', 'kültür', 'sanat', 'müzik',
      'film', 'resim', 'bilgi', 'haber', 'sistem', 'program', 'bilgisayar', 'telefon', 'internet', 'düzen',
      'kural', 'hukuk', 'adalet', 'özgürlük', 'barış', 'saygı', 'güven', 'umut', 'mutluluk', 'üzüntü',
      'renk', 'beyaz', 'siyah', 'kırmızı', 'mavi', 'yeşil', 'sarı', 'sıcak', 'soğuk', 'yaz', 'kış',
      'bahar', 'sonbahar', 'rüzgâr', 'yağmur', 'kar', 'hayvan', 'kuş', 'balık', 'kedi', 'köpek', 'at',
      'meyve', 'elma', 'üzüm', 'ekmek', 'çay', 'yemek', 'sofra', 'oda', 'kapı', 'pencere', 'masa',
    ],
  },
  german: {
    label: 'Deutsch',
    words: [
      'der', 'die', 'das', 'und', 'in', 'zu', 'den', 'von', 'sie', 'mit', 'des', 'sich', 'auf', 'für',
      'ist', 'im', 'dem', 'nicht', 'ein', 'eine', 'als', 'auch', 'es', 'an', 'werden', 'aus', 'er', 'hat',
      'dass', 'sein', 'wird', 'bei', 'einer', 'wir', 'was', 'noch', 'nach', 'wie', 'wenn', 'nur', 'oder',
      'aber', 'vor', 'zur', 'bis', 'mehr', 'durch', 'man', 'sehr', 'zum', 'über', 'so', 'hier', 'ich',
      'schon', 'immer', 'jetzt', 'dann', 'alle', 'jahr', 'zeit', 'tag', 'mensch', 'kind', 'leben', 'welt',
      'land', 'stadt', 'haus', 'arbeit', 'frage', 'antwort', 'wort', 'sprache', 'buch', 'schule', 'lehrer',
      'freund', 'familie', 'mutter', 'vater', 'hand', 'auge', 'kopf', 'herz', 'wasser', 'luft', 'sonne',
      'himmel', 'erde', 'berg', 'baum', 'blume', 'meer', 'fluss', 'wald', 'weg', 'straße', 'tür', 'fenster',
      'tisch', 'zimmer', 'geld', 'preis', 'markt', 'ding', 'sache', 'grund', 'ziel', 'idee', 'gedanke',
      'problem', 'lösung', 'beispiel', 'zahl', 'teil', 'gruppe', 'system', 'programm', 'rechner', 'handy',
      'wissen', 'denken', 'sagen', 'machen', 'gehen', 'kommen', 'geben', 'nehmen', 'sehen', 'lesen',
      'schreiben', 'lernen', 'arbeiten', 'wohnen', 'spielen', 'finden', 'bleiben', 'stehen', 'halten',
      'beginnen', 'warten', 'lieben', 'wollen', 'können', 'müssen', 'sollen', 'dürfen', 'gut', 'schlecht',
      'schön', 'groß', 'klein', 'neu', 'alt', 'jung', 'lang', 'kurz', 'schnell', 'langsam', 'leicht',
      'schwer', 'richtig', 'falsch', 'offen', 'hoch', 'tief', 'weit', 'nah', 'erste', 'letzte', 'ganz',
      'viele', 'wenig', 'andere', 'gleich', 'eigen', 'wichtig', 'möglich', 'nötig', 'zusammen', 'wieder',
      'heute', 'morgen', 'gestern', 'nacht', 'woche', 'monat', 'stunde', 'minute', 'farbe', 'weiß',
      'schwarz', 'rot', 'blau', 'grün', 'gelb', 'warm', 'kalt', 'sommer', 'winter', 'frühling', 'herbst',
      'wind', 'regen', 'schnee', 'tier', 'vogel', 'fisch', 'katze', 'hund', 'pferd', 'brot', 'essen',
    ],
  },
  french: {
    label: 'Français',
    words: [
      'le', 'de', 'un', 'être', 'et', 'à', 'il', 'avoir', 'ne', 'je', 'son', 'que', 'se', 'qui', 'ce',
      'dans', 'en', 'du', 'elle', 'au', 'pour', 'pas', 'que', 'vous', 'par', 'sur', 'faire', 'plus',
      'dire', 'me', 'on', 'mon', 'lui', 'nous', 'comme', 'mais', 'pouvoir', 'avec', 'tout', 'aller',
      'voir', 'bien', 'où', 'sans', 'tu', 'ou', 'leur', 'homme', 'si', 'deux', 'même', 'prendre', 'aussi',
      'celui', 'donner', 'temps', 'très', 'savoir', 'falloir', 'voilà', 'jour', 'venir', 'monde', 'enfant',
      'femme', 'vie', 'main', 'chose', 'mot', 'pays', 'ville', 'maison', 'école', 'travail', 'ami',
      'famille', 'mère', 'père', 'eau', 'air', 'soleil', 'ciel', 'terre', 'arbre', 'fleur', 'mer',
      'rivière', 'forêt', 'montagne', 'route', 'rue', 'porte', 'fenêtre', 'table', 'chambre', 'livre',
      'langue', 'question', 'réponse', 'idée', 'pensée', 'raison', 'but', 'résultat', 'exemple', 'nombre',
      'partie', 'groupe', 'système', 'programme', 'problème', 'solution', 'argent', 'prix', 'marché',
      'service', 'penser', 'parler', 'écrire', 'lire', 'apprendre', 'travailler', 'vivre', 'trouver',
      'mettre', 'rester', 'tenir', 'commencer', 'attendre', 'aimer', 'vouloir', 'devoir', 'croire',
      'bon', 'mauvais', 'beau', 'grand', 'petit', 'nouveau', 'vieux', 'jeune', 'long', 'court', 'rapide',
      'lent', 'facile', 'difficile', 'vrai', 'faux', 'ouvert', 'haut', 'bas', 'loin', 'près', 'premier',
      'dernier', 'entier', 'autre', 'chaque', 'plusieurs', 'peu', 'beaucoup', 'important', 'possible',
      'nécessaire', 'ensemble', 'encore', 'toujours', 'jamais', 'parfois', 'maintenant', 'aujourd',
      'demain', 'hier', 'nuit', 'matin', 'soir', 'semaine', 'mois', 'année', 'heure', 'minute',
      'couleur', 'blanc', 'noir', 'rouge', 'bleu', 'vert', 'jaune', 'chaud', 'froid', 'été', 'hiver',
      'vent', 'pluie', 'neige', 'animal', 'oiseau', 'poisson', 'chat', 'chien', 'cheval', 'pain',
    ],
  },
  spanish: {
    label: 'Español',
    words: [
      'el', 'de', 'que', 'y', 'la', 'en', 'un', 'ser', 'se', 'no', 'haber', 'por', 'con', 'su', 'para',
      'como', 'estar', 'tener', 'le', 'lo', 'todo', 'pero', 'más', 'hacer', 'o', 'poder', 'decir', 'este',
      'ir', 'otro', 'ese', 'si', 'me', 'ya', 'ver', 'porque', 'dar', 'cuando', 'muy', 'sin', 'sobre',
      'también', 'hasta', 'año', 'dos', 'querer', 'entre', 'así', 'primero', 'desde', 'grande', 'saber',
      'tiempo', 'mismo', 'día', 'vida', 'hombre', 'mujer', 'niño', 'familia', 'casa', 'ciudad', 'país',
      'mundo', 'trabajo', 'escuela', 'amigo', 'madre', 'padre', 'mano', 'ojo', 'agua', 'aire', 'sol',
      'cielo', 'tierra', 'árbol', 'flor', 'mar', 'río', 'bosque', 'montaña', 'camino', 'calle', 'puerta',
      'ventana', 'mesa', 'cuarto', 'libro', 'palabra', 'lengua', 'pregunta', 'respuesta', 'idea', 'razón',
      'objetivo', 'resultado', 'ejemplo', 'número', 'parte', 'grupo', 'sistema', 'programa', 'problema',
      'solución', 'dinero', 'precio', 'mercado', 'servicio', 'pensar', 'hablar', 'escribir', 'leer',
      'aprender', 'trabajar', 'vivir', 'encontrar', 'poner', 'quedar', 'empezar', 'esperar', 'amar',
      'deber', 'creer', 'bueno', 'malo', 'bonito', 'pequeño', 'nuevo', 'viejo', 'joven', 'largo', 'corto',
      'rápido', 'lento', 'fácil', 'difícil', 'verdadero', 'falso', 'abierto', 'alto', 'bajo', 'lejos',
      'cerca', 'último', 'entero', 'cada', 'varios', 'poco', 'mucho', 'importante', 'posible', 'necesario',
      'junto', 'todavía', 'siempre', 'nunca', 'aveces', 'ahora', 'hoy', 'mañana', 'ayer', 'noche',
      'semana', 'mes', 'hora', 'minuto', 'color', 'blanco', 'negro', 'rojo', 'azul', 'verde', 'amarillo',
      'caliente', 'frío', 'verano', 'invierno', 'primavera', 'otoño', 'viento', 'lluvia', 'nieve',
      'animal', 'pájaro', 'pez', 'gato', 'perro', 'caballo', 'pan', 'comida', 'fruta', 'manzana',
    ],
  },
  italian: {
    label: 'Italiano',
    words: [
      'il', 'di', 'che', 'e', 'la', 'in', 'un', 'essere', 'a', 'per', 'non', 'avere', 'con', 'si', 'come',
      'da', 'su', 'io', 'lo', 'ma', 'più', 'anche', 'fare', 'tutto', 'questo', 'quello', 'se', 'dire',
      'noi', 'loro', 'potere', 'volere', 'dovere', 'andare', 'vedere', 'sapere', 'dare', 'stare', 'venire',
      'quando', 'perché', 'molto', 'senza', 'ancora', 'sempre', 'mai', 'ora', 'oggi', 'domani', 'ieri',
      'anno', 'giorno', 'tempo', 'vita', 'uomo', 'donna', 'bambino', 'famiglia', 'casa', 'città', 'paese',
      'mondo', 'lavoro', 'scuola', 'amico', 'madre', 'padre', 'mano', 'occhio', 'acqua', 'aria', 'sole',
      'cielo', 'terra', 'albero', 'fiore', 'mare', 'fiume', 'bosco', 'montagna', 'strada', 'via', 'porta',
      'finestra', 'tavolo', 'stanza', 'libro', 'parola', 'lingua', 'domanda', 'risposta', 'idea', 'ragione',
      'scopo', 'risultato', 'esempio', 'numero', 'parte', 'gruppo', 'sistema', 'programma', 'problema',
      'soluzione', 'denaro', 'prezzo', 'mercato', 'servizio', 'pensare', 'parlare', 'scrivere', 'leggere',
      'imparare', 'lavorare', 'vivere', 'trovare', 'mettere', 'restare', 'tenere', 'cominciare',
      'aspettare', 'amare', 'credere', 'buono', 'cattivo', 'bello', 'grande', 'piccolo', 'nuovo',
      'vecchio', 'giovane', 'lungo', 'corto', 'veloce', 'lento', 'facile', 'difficile', 'vero', 'falso',
      'aperto', 'alto', 'basso', 'lontano', 'vicino', 'primo', 'ultimo', 'intero', 'altro', 'ogni',
      'diversi', 'poco', 'importante', 'possibile', 'necessario', 'insieme', 'notte', 'mattina', 'sera',
      'settimana', 'mese', 'ora', 'minuto', 'colore', 'bianco', 'nero', 'rosso', 'blu', 'verde', 'giallo',
      'caldo', 'freddo', 'estate', 'inverno', 'primavera', 'autunno', 'vento', 'pioggia', 'neve',
      'animale', 'uccello', 'pesce', 'gatto', 'cane', 'cavallo', 'pane', 'cibo', 'frutta', 'mela',
    ],
  },
  portuguese: {
    label: 'Português',
    words: [
      'o', 'de', 'que', 'e', 'a', 'em', 'um', 'ser', 'para', 'com', 'não', 'por', 'se', 'como', 'mas',
      'do', 'da', 'no', 'na', 'ter', 'estar', 'fazer', 'mais', 'ou', 'quando', 'muito', 'já', 'também',
      'sem', 'sobre', 'até', 'isso', 'este', 'esse', 'poder', 'dizer', 'ir', 'ver', 'saber', 'dar',
      'ficar', 'vir', 'ano', 'dia', 'tempo', 'vida', 'homem', 'mulher', 'criança', 'família', 'casa',
      'cidade', 'país', 'mundo', 'trabalho', 'escola', 'amigo', 'mãe', 'pai', 'mão', 'olho', 'água',
      'ar', 'sol', 'céu', 'terra', 'árvore', 'flor', 'mar', 'rio', 'floresta', 'montanha', 'caminho',
      'rua', 'porta', 'janela', 'mesa', 'quarto', 'livro', 'palavra', 'língua', 'pergunta', 'resposta',
      'ideia', 'razão', 'objetivo', 'resultado', 'exemplo', 'número', 'parte', 'grupo', 'sistema',
      'programa', 'problema', 'solução', 'dinheiro', 'preço', 'mercado', 'serviço', 'pensar', 'falar',
      'escrever', 'ler', 'aprender', 'trabalhar', 'viver', 'encontrar', 'colocar', 'começar', 'esperar',
      'amar', 'querer', 'dever', 'acreditar', 'bom', 'mau', 'bonito', 'grande', 'pequeno', 'novo',
      'velho', 'jovem', 'longo', 'curto', 'rápido', 'lento', 'fácil', 'difícil', 'verdadeiro', 'falso',
      'aberto', 'alto', 'baixo', 'longe', 'perto', 'primeiro', 'último', 'inteiro', 'outro', 'cada',
      'vários', 'pouco', 'importante', 'possível', 'necessário', 'junto', 'ainda', 'sempre', 'nunca',
      'agora', 'hoje', 'amanhã', 'ontem', 'noite', 'manhã', 'tarde', 'semana', 'mês', 'hora', 'minuto',
      'cor', 'branco', 'preto', 'vermelho', 'azul', 'verde', 'amarelo', 'quente', 'frio', 'verão',
      'inverno', 'primavera', 'outono', 'vento', 'chuva', 'neve', 'animal', 'pássaro', 'peixe', 'gato',
      'cachorro', 'cavalo', 'pão', 'comida', 'fruta', 'maçã', 'história', 'cultura', 'arte', 'música',
    ],
  },
  arabic: {
    label: 'العربية',
    words: [
      'في', 'من', 'على', 'أن', 'إلى', 'عن', 'مع', 'هذا', 'هذه', 'ذلك', 'التي', 'الذي', 'كان', 'كل',
      'بعد', 'قبل', 'بين', 'عند', 'حتى', 'لكن', 'أو', 'ثم', 'قد', 'لا', 'ما', 'هل', 'أين', 'كيف',
      'لماذا', 'متى', 'يوم', 'سنة', 'شهر', 'أسبوع', 'ساعة', 'وقت', 'حياة', 'إنسان', 'رجل', 'امرأة',
      'طفل', 'أسرة', 'بيت', 'مدينة', 'بلد', 'عالم', 'عمل', 'مدرسة', 'صديق', 'أم', 'أب', 'يد', 'عين',
      'رأس', 'قلب', 'ماء', 'هواء', 'شمس', 'سماء', 'أرض', 'شجرة', 'زهرة', 'بحر', 'نهر', 'غابة', 'جبل',
      'طريق', 'شارع', 'باب', 'نافذة', 'طاولة', 'غرفة', 'كتاب', 'كلمة', 'لغة', 'سؤال', 'جواب', 'فكرة',
      'سبب', 'هدف', 'نتيجة', 'مثال', 'رقم', 'عدد', 'جزء', 'مجموعة', 'نظام', 'برنامج', 'مشكلة', 'حل',
      'مال', 'سعر', 'سوق', 'خدمة', 'علم', 'معرفة', 'خبر', 'قصة', 'تاريخ', 'ثقافة', 'فن', 'موسيقى',
      'صورة', 'حاسوب', 'هاتف', 'شبكة', 'تقنية', 'معلومة', 'مجتمع', 'فريق', 'مدير', 'عامل', 'مهنة',
      'واجب', 'حق', 'قانون', 'عدل', 'حرية', 'سلام', 'احترام', 'ثقة', 'أمل', 'سعادة', 'حزن', 'حب',
      'يكتب', 'يقرأ', 'يعمل', 'يعيش', 'يفكر', 'يفهم', 'يجد', 'يضع', 'يقف', 'يبدأ', 'ينتهي', 'ينتظر',
      'يحب', 'يريد', 'يستطيع', 'يجب', 'يمكن', 'يأتي', 'يذهب', 'يعطي', 'يأخذ', 'يرى', 'يعرف', 'يقول',
      'جيد', 'سيء', 'جميل', 'كبير', 'صغير', 'جديد', 'قديم', 'طويل', 'قصير', 'سريع', 'بطيء', 'سهل',
      'صعب', 'صحيح', 'خطأ', 'مفتوح', 'عالي', 'منخفض', 'بعيد', 'قريب', 'أول', 'أخير', 'كامل', 'آخر',
      'بعض', 'قليل', 'كثير', 'مهم', 'ممكن', 'ضروري', 'معا', 'دائما', 'أبدا', 'أحيانا', 'الآن', 'اليوم',
      'غدا', 'أمس', 'ليل', 'صباح', 'مساء', 'لون', 'أبيض', 'أسود', 'أحمر', 'أزرق', 'أخضر', 'أصفر',
      'حار', 'بارد', 'صيف', 'شتاء', 'ربيع', 'خريف', 'ريح', 'مطر', 'ثلج', 'حيوان', 'طائر', 'سمك',
      'قط', 'كلب', 'حصان', 'خبز', 'طعام', 'فاكهة', 'تفاح', 'شاي', 'حليب', 'عسل', 'صوت', 'طاقة',
    ],
  },
};
